[package]
name = "loper-db-proto-rs"
version = "0.1.0"
edition = "2021"
publish = false

workspace = "../../"

[dependencies]
tonic = "^0.8.3"
prost = "^0.11.6"

[build-dependencies]
tonic-build = "^0.8.3"