[package]
name = "loper-db-web-extension"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

workspace = "../../"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "1"
loper-db-proto-rs = { path = "../loper-db-proto-rs", features = ["grpc-client"]  }
tonic = "^0.8.3"
prost = "^0.11.6"
once_cell = "1.17.0"
tokio = { version = "^1.24.2", features = ["rt", "rt-multi-thread", "sync"] }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6", "channel-api"]