name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  proxy:
    name: Proxy node-${{ matrix.node_version }}-${{ matrix.system.target }}-${{ matrix.system.os }}
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16
        system:
          - os: macos-11
            target: x86_64-apple-darwin
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: windows-2022
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3

      - name: Setup Yarn Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-native-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-native-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.system.target }}
          override: true
      - name: Setup Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ github.token }}

      - name: Install node modules
        run: yarn install

      - name: Build loper-db-web-proxy module
        run: yarn workspace @ankoh/loper-db-web-proxy build:release


  app:
    name: App
    runs-on: ubuntu-latest
    needs: [proxy]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Yarn Cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules/
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-wasm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - name: Setup Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ github.token }}

      - name: Install npm dependencies
        run: yarn install

      - name: Generate protobuf files
        run: buf generate --verbose

      - name: Build loper-db-proto-es module
        run: yarn workspace @ankoh/loper-db-proto-es build
      - name: Build loper-db-web-shell module 
        run: yarn workspace @ankoh/loper-db-web-shell build:release
      - name: Build loper-db-web-proxy module
        run: yarn workspace @ankoh/loper-db-web-proxy build:release
      - name: Build loper-db-web-app
        run: yarn workspace @ankoh/loper-db-web-app build:pwa:release

      - name: Deploy GitHub Page
        if: github.ref == 'refs/heads/main'
        run: |
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git fetch origin gh-pages
            ./scripts/deploy_pages.sh
