name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Buf
      uses: bufbuild/buf-setup-action@v1.9.0
      with:
        github_token: ${{ github.token }}

    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: Install npm dependencies
      run: yarn install

    - name: Generate protobuf library
      run: buf generate --verbose

    - name: Build loper-db-proto-es library
      run: yarn workspace @ankoh/loper-db-proto-es build

    - name: Build loper-db-web-shell library 
      run: yarn workspace @ankoh/loper-db-web-shell build:release

    - name: Build loper-db-web-proxy binary
      run: yarn workspace @ankoh/loper-db-web-proxy build:release

    - name: Build loper-db-web-app
      run: yarn workspace @ankoh/loper-db-web-app build:pwa:release

    - name: Deploy GitHub Page
      if: github.ref == 'refs/heads/main'
      run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git fetch origin gh-pages
          ./scripts/deploy_pages.sh
